### ISSUE TITLE
modify_by_filed broke ordered_non_unique iteration

### ISSUE THREAD

**Issue by chenyukang** [lun3x/multi_index_map#22]
This code expect to run successfully:

```rust
use multi_index_map::MultiIndexMap;

#[derive(MultiIndexMap, Debug, Clone)]
pub(crate) struct Order {
    #[multi_index(hashed_unique)]
    pub(crate) order_id: u32,
    #[multi_index(ordered_non_unique)]
    pub(crate) timestamp: u64,
    #[multi_index(hashed_non_unique)]
    pub(crate) trader_name: String,
}

fn main() {
    let o1 = Order {
        order_id: 1,
        timestamp: 111,
        trader_name: "John".to_string(),
    };

    let o2 = Order {
        order_id: 2,
        timestamp: 22,
        trader_name: "Mike".to_string(),
    };

    let o3 = Order {
        order_id: 3,
        timestamp: 33,
        trader_name: "Tom".to_string(),
    };

    let o4 = Order {
        order_id: 4,
        timestamp: 44,
        trader_name: "Jerry".to_string(),
    };

    let mut map = MultiIndexOrderMap::default();

    map.insert(o1.clone());
    map.insert(o2);
    map.insert(o3);
    map.insert(o4);

    for o in map.iter_by_timestamp() {
        eprintln!("iter_by_timestamp: {o:?}")
    }

    map.modify_by_order_id(&1, |o| {
        o.timestamp = 0;
    });

    eprintln!("===========");
    for o in map.iter_by_timestamp() {
        eprintln!("iter_by_timestamp: {o:?}");
    }
}
```

There is a crash when iterate by `timestamp`:
```console
map git:(master) ✗ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/map`
iter_by_timestamp: Order { order_id: 2, timestamp: 22, trader_name: "Mike" }
iter_by_timestamp: Order { order_id: 3, timestamp: 33, trader_name: "Tom" }
iter_by_timestamp: Order { order_id: 4, timestamp: 44, trader_name: "Jerry" }
iter_by_timestamp: Order { order_id: 1, timestamp: 111, trader_name: "John" }
===========
iter_by_timestamp: Order { order_id: 1, timestamp: 0, trader_name: "John" }
iter_by_timestamp: Order { order_id: 2, timestamp: 22, trader_name: "Mike" }
iter_by_timestamp: Order { order_id: 3, timestamp: 33, trader_name: "Tom" }
iter_by_timestamp: Order { order_id: 4, timestamp: 44, trader_name: "Jerry" }
thread 'main' panicked at 'Internal invariants broken, found empty slice in non_unique index 'timestamp'', src/main.rs:3:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/option.rs:1952:5
   5: core::option::Option<T>::expect
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/option.rs:912:21
   6: <map::MultiIndexOrderMapTimestampIter as core::iter::traits::iterator::Iterator>::next
             at ./src/main.rs:3:10
   7: map::main
             at ./src/main.rs:54:14
   8: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lun3x** [comment]
should be fixed now @wyjin's PR is merged
